[tool.poetry]
name = "pythonProject"
version = "0.1.0"
description = ""
readme = "README.md"
packages = [
    { include = "mini_mip_system" },  # Add your project folder here
]

[tool.poetry.dependencies]
python = "^3.11.9"
torch = "^2.5.1"
torchvision = "^0.20.1"
flwr-datasets = "^0.4.0"
scipy = "^1.15.1"
statsmodels = "^0.14.4"
flask = "^3.1.0"
grpcio = "^1.71.0"
protobuf = "5.29.0"
pandas = "^2.2.3"
duckdb = "1.2.1"
scikit-learn = "^1.6.1"
tdigest = "^0.5.2.2"
crick = "^0.0.8"
antlr4-python3-runtime = "4.9.3"
psycopg2-binary = "^2.9.10"

kagglehub = "*"
pytest = "^7.4.2"
mord = "^0.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"